README.md
docs/quick_start.md

- Add a first version of Quick start page.
- Let's leave readme as it is for now and update it once the first version of doc is published.
- #169 
- N/A

doc: add a first version of Quick start page

---

CHANGELOG.md
src/crawlee/autoscaling/autoscaled_pool.py
src/crawlee/basic_crawler/basic_crawler.py
tests/unit/basic_crawler/test_basic_crawler.py
tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py

- Add max requests per crawl to `BasicCrawler`.
- #173 
- A new unit test was implemented
Code sample for manual replication:
```python
import asyncio
import logging
from crawlee.autoscaling import ConcurrencySettings
from crawlee.beautifulsoup_crawler import BeautifulSoupCrawler, BeautifulSoupCrawlingContext
logging.basicConfig(level=logging.INFO)
async def main() -> None:
crawler = BeautifulSoupCrawler(
concurrency_settings=ConcurrencySettings(max_concurrency=1),
max_requests_per_crawl=4,
)
@crawler.router.default_handler
async def request_handler(context: BeautifulSoupCrawlingContext) -> None:
await context.enqueue_links()
data = {
'url': context.request.url,
'title': context.soup.title.string if context.soup.title else None,
}
await context.push_data(data)
await …
```

feat: add max requests per crawl to `BasicCrawler`

---

pyproject.toml

Adds support for decompressing a brotli-compressed server response if an "Accept-Encoding" header was passed with the "br"  or "gzip, deflate, br" parameter and the server supports this type of compression.
Httpx provides the necessary functionality, but requires additional libraries to be installed to work correctly.

feat: add support decompress *br* response content

---

CHANGELOG.md
src/crawlee/basic_crawler/basic_crawler.py
src/crawlee/basic_crawler/types.py
src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
src/crawlee/http_crawler/http_crawler.py
src/crawlee/playwright_crawler/playwright_crawler.py
tests/unit/basic_crawler/test_context_pipeline.py
tests/unit/basic_crawler/test_router.py

feat: automatic logging setup

---

src/crawlee/storages/request_queue.py

- Set `ensure_consistency` to `False` in the request queue.
- Just a hotfix, in #203 is more information.
- #203 
- All tests pass successfully.

fix: do not wait for consistency in request queue

---

CHANGELOG.md
src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py

fix: Selector handling in BeautifulSoupCrawler enqueue_links

---

CHANGELOG.md
src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py

Replaced `find` to `select_one` because `find` does not support CSS selectors, which caused incorrect behavior.
#230

fix: handle blocked request

---

templates/beautifulsoup/{{cookiecutter.project_name}}/pyproject.toml
templates/playwright/{{cookiecutter.project_name}}/pyproject.toml

so we do not have to do things like https://github.com/apify/crawlee-python/pull/247

chore: use latest crawlee version in templates

---

src/crawlee/cli.py
src/crawlee/http_clients/httpx_client.py
website/generate_module_shortcuts.py

fix: CLI UX improvements

---

CHANGELOG.md
src/crawlee/autoscaling/__init__.py
src/crawlee/base_storage_client/__init__.py
src/crawlee/basic_crawler/__init__.py
src/crawlee/beautifulsoup_crawler/__init__.py
src/crawlee/browsers/__init__.py
src/crawlee/events/__init__.py
src/crawlee/http_clients/__init__.py
src/crawlee/http_crawler/__init__.py
src/crawlee/memory_storage_client/__init__.py
src/crawlee/playwright_crawler/__init__.py
src/crawlee/sessions/__init__.py
src/crawlee/statistics/__init__.py
src/crawlee/storages/__init__.py

- Fix Pylance `reportPrivateImportUsage` errors by defining `__all__` in modules `__init__.py`.
- Closes: #283
- N/A

fix: Pylance reportPrivateImportUsage errors

---

CHANGELOG.md
src/crawlee/basic_crawler/basic_crawler.py

- fix: set httpx logging to warning
- Closes: #302 
- N/A

fix: set httpx logging to warning

---

CHANGELOG.md
src/crawlee/cli.py
tests/unit/cli/test_create.py

- closes #301
Typer bit me quite hard here, but we should be out of the dark now.

fix: project bootstrapping in existing folder

---

src/crawlee/basic_crawler/basic_crawler.py
src/crawlee/playwright_crawler/playwright_crawler.py
tests/unit/playwright_crawler/test_playwright_crawler.py

fix: Also use error_handler for context pipeline errors

---

src/crawlee/_utils/urls.py
src/crawlee/basic_crawler/basic_crawler.py
src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
src/crawlee/http_clients/httpx_client.py
src/crawlee/models.py
src/crawlee/playwright_crawler/playwright_crawler.py
src/crawlee/proxy_configuration.py
tests/unit/_utils/test_urls.py
tests/unit/basic_crawler/test_basic_crawler.py
tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
tests/unit/http_crawler/test_http_crawler.py
tests/unit/memory_storage_client/test_request_queue_client.py
tests/unit/playwright_crawler/test_playwright_crawler.py
tests/unit/storages/test_request_queue.py

- `context.request.url` is a string, but URL validation is kept
- N/A
- Tests pass

refactor: `context.request.url` is string

---

src/crawlee/storages/dataset.py

fix: Warn instead of crashing when an empty dataset is being exported

---

README.md

If we would like to add a test coverage badge, we would need to utilize some 3rd part service like [Codecov](https://codecov.io/) or [Coveralls](https://coveralls.io/).

chore: add basic badges to readme

---

src/crawlee/basic_crawler/basic_crawler.py
tests/unit/basic_crawler/test_basic_crawler.py

This makes sure that storages opened via `BasicCrawler.get_dataset` and the like will use the same configuration object as the crawler. While this is relevant to #351, it does not fully resolve it (see #152).

fix: pass crawler configuration to storages

---

README.md
docs/introduction/01-setting-up.mdx
docs/quick-start/index.mdx
pyproject.toml
src/crawlee/http_clients/__init__.py
src/crawlee/http_clients/curl_impersonate.py
tests/unit/http_clients/test_curl_impersonate.py

- do not import curl impersonate in http clients init
- add extra all for installing everything
- minor improvement of readme & intro docs
N/A
N/A

fix: do not import curl impersonate in http clients init

---

pyproject.toml
src/crawlee/_utils/file.py
src/crawlee/memory_storage_client/_creation_management.py
src/crawlee/memory_storage_client/dataset_client.py
src/crawlee/memory_storage_client/key_value_store_client.py
src/crawlee/memory_storage_client/memory_storage_client.py
src/crawlee/memory_storage_client/request_queue_client.py
tests/unit/_utils/test_file.py
tests/unit/memory_storage_client/test_creation_management.py

- closes #412
This is slightly uglier, but friendlier to type checkers and makes Crawlee's footprint a little smaller.

refactor: Remove dependency on aiofiles and aioshutil

---

src/crawlee/_utils/urls.py
src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
src/crawlee/parsel_crawler/parsel_crawler.py
src/crawlee/playwright_crawler/playwright_crawler.py
tests/unit/_utils/test_urls.py

- If it starts with `//`, replace it with the same protocol.
- To avoid unsupported protocols, such as `mailto` and `tel`, we only allow writing `http` and `https`.
- Closes: #417 
- Add a unit test for cases that start with `//`.

fix: Relative URLS supports & If not a URL, pass #417

---

website/package.json
website/src/theme/DocItem/Layout/index.js
website/src/theme/DocSidebar/Desktop/Content/index.js
website/src/theme/NavbarItem/ComponentTypes.js
website/yarn.lock

Partially reverts https://github.com/apify/crawlee-python/pull/450 and fixes the underlying issues. Bumps `@apify/docusaurus-plugin-typedoc-api` to `4.2.2` to support higher versions of Docusaurus.
Not a priority, but I think it's better to merge now than wait until we actually need to bump Docusaurus for some other reason.

docs: unpin Docusaurus version, fix build

---

src/crawlee/__init__.py

Without the top-level `__all__`, `pyright` screams at `from crawlee import Request`, for example

fix: Add missing __all__ to top-level __init__.py file

---

.github/workflows/run_release.yaml

Everything that is merged to master passed through code checks before, and they're needlessly long.

ci: Skip running code checks on release

---

pyproject.toml

- Remove the upper version boundary of dependencies
- Alphabetize them
- Remove patch-level requirements
- Relates to https://github.com/apify/apify-sdk-python/pull/254
- N/A
- N/A

chore: remove upper version boundary of deps

---

src/crawlee/http_clients/curl_impersonate.py

- `CurlImpersonateHttpClient` selects chrome browser type for impersonation by default.
- Before:
```json
{
"url": "https://httpbin.org/get",
"response": {
"args": {},
"headers": {
"Accept": "*/*",
"Accept-Encoding": "gzip, deflate, br",
"Content-Type": "application/x-www-form-urlencoded",
"Host": "httpbin.org",
"X-Amzn-Trace-Id": "Root=1-66d04355-5df0396b08e2931c125389aa"
},
"origin": "78.80.81.196",
"url": "https://httpbin.org/get"
}
}
```
- After:
```json
{
"url": "https://httpbin.org/get",
"response": {
"args": {},
"headers": {
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
"Accept-Encoding": "gzip, deflate, br, zstd",
"Accept-Language": "en-US,en;q=0.9",
"Content-Type": …
```

feat: curl http client selects chrome impersonation by default

---

pyproject.toml

1.27 is the lowest version I'm comfortable supporting - it adds helper functions to locators that we may want to use in the future. It's ~2 years old, so it should be OK.

chore(deps): Relax Playwright version constraint

---

pyproject.toml

This prevents dependency conflicts with playwright (requires 11.0.0)

chore(deps): Relax pyee dependency version constraint

---

src/crawlee/storages/_request_provider.py

This should fix the issue mentioned in https://github.com/apify/apify-sdk-python/pull/261#issuecomment-2329084944

fix: Deduplicate requests by unique key before submitting them to the queue

---

src/crawlee/_utils/http.py
src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/errors.py
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_httpx.py
src/crawlee/http_clients/curl_impersonate.py
tests/unit/http_crawler/test_http_crawler.py
tests/unit/parsel_crawler/test_parsel_crawler.py

- Error codes between 400 and 599 are considered as errors by default.
- Before this change only codes between 500 and 599 were handled by default.
- Closes: #496
- I added a new test to test that 4xx status codes are not being retried.

fix: http clients detect 4xx as errors by default

---

src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/storages/_request_list.py
src/crawlee/storages/_request_provider.py
src/crawlee/storages/_request_queue.py
tests/unit/storages/test_request_queue.py

- Simplify type of request(s) args to only string or Request.
- Should be only internal change, not breaking, as `BaseRequestData` was not exposed to the public in v0.3.
- Closes: N/A
- N/A

refactor: simplify type of request(s) args

---

src/crawlee/_log_config.py
src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/configuration.py

- The `CRAWLEE_VERBOSE` and `CRAWLEE_LOG_LEVEL` variables are now respected by crawlee
- `CrawleeLogFormatter` doesn't alter the record being formatted anymore
- SDK counterpart coming soon

fix: Correctly handle log level configuration

---

pyproject.toml
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_httpx.py
src/crawlee/http_clients/curl_impersonate.py
tests/unit/http_clients/test_httpx.py

- Add HTTP/2 support for HTTPX client.
- Closes #512
- New unit tests were added.

feat: add HTTP/2 support for HTTPX client

---

pyproject.toml
src/crawlee/_request.py
src/crawlee/_types.py
src/crawlee/_utils/http.py
src/crawlee/_utils/requests.py
src/crawlee/fingerprint_suite/_consts.py
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_httpx.py
src/crawlee/http_clients/curl_impersonate.py
src/crawlee/memory_storage_client/_request_queue_client.py
src/crawlee/playwright_crawler/_utils.py
tests/unit/_utils/test_requests.py
tests/unit/fingerprint_suite/test_header_generator.py
tests/unit/proxy_configuration/test_tiers.py
tests/unit/test_service_container.py

- Version 1.7.2 of `curl-cffi` introduces breaking changes.
- This update includes adopting the new version, adding type aliases for `Request` fields, and incorporating other minor changes from PR #542.
- N/A (ad-hoc fix)
- The current set of unit tests should cover the changes.

fix: adopt new version of curl-cffi

---

src/crawlee/_types.py
src/crawlee/browsers/_base_browser_controller.py
src/crawlee/browsers/_base_browser_plugin.py
src/crawlee/browsers/_browser_pool.py
src/crawlee/browsers/_playwright_browser_controller.py
src/crawlee/browsers/_playwright_browser_plugin.py
src/crawlee/browsers/_types.py
src/crawlee/fingerprint_suite/_consts.py
src/crawlee/fingerprint_suite/_header_generator.py
src/crawlee/http_clients/_httpx.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/storages/_dataset.py
tests/unit/fingerprint_suite/test_header_generator.py
tests/unit/http_clients/test_httpx.py
tests/unit/playwright_crawler/test_playwright_crawler.py

- See the issue description for more information.
- Playwright headless Chromium before:
```json
{
"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
"Accept-Encoding": "gzip, deflate, br, zstd",
"Host": "httpbin.org",
"Priority": "u=0, i",
"Sec-Ch-Ua": "\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"HeadlessChrome\";v=\"128\"",
"Sec-Ch-Ua-Mobile": "?0",
"Sec-Ch-Ua-Platform": "\"Linux\"",
"Sec-Fetch-Dest": "document",
"Sec-Fetch-Mode": "navigate",
"Sec-Fetch-Site": "none",
"Sec-Fetch-User": "?1",
"Upgrade-Insecure-Requests": "1",
"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/128.0.6613.18 Safari/537.36",
"X-Amzn-Trace-Id": …
```

feat: mask Playwright's "headless" headers

---

src/crawlee/basic_crawler/_basic_crawler.py
tests/unit/basic_crawler/test_basic_crawler.py

fix: call `error_handler` for `SessionError`

---

src/crawlee/_request.py

This is needed for Apify SDK tests

fix: Add equality check to UserData model

---

pyproject.toml

To resolve the deprecation warning:
```
warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
ready: 12/16 workers/home/vdusek/Projects/crawlee-python/.venv/lib/python3.12/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
```

chore: set pytest-asyncio loop scope to function

---

src/crawlee/_request.py
src/crawlee/_types.py

- closes #563
@tlinhart any chance you could test this and confirm it fixes the issue?

fix: Workaround for JSON value typing problems

---

src/crawlee/_types.py
src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
src/crawlee/http_crawler/_http_crawler.py
src/crawlee/parsel_crawler/_parsel_crawler.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/storages/_dataset.py
tests/unit/basic_crawler/test_basic_crawler.py
tests/unit/basic_crawler/test_context_pipeline.py
tests/unit/test_router.py

- This adds a `get_key_value_store(id, name)` context helper to `BasicCrawlingContext`
- Also, push_data calls are held until the request handler terminates successfully (same as in JS version)
- This is necessary for adaptive crawling (#249), among other things

feat: Key-value store context helpers

---

src/crawlee/configuration.py
website/build_api_reference.sh
website/docusaurus.config.js
website/package.json
website/pydoc-markdown/generate_ast.py
website/pydoc-markdown/google_docstring_processor.py
website/src/css/custom.css
website/transformDocs.js
website/yarn.lock

- Reapplies the changes from `docs: add Google-style docstring parser` from [SDK](https://github.com/apify/apify-sdk-python/commit/2e000e9c6889d5c41f28a07414cd84505e9d00b1) (renders commented function arguments)
- Renders the object attributes (from the class docstring)
- Documents class inheritance properly now
- Renders inherited symbols (e.g. `BasicCrawler` symbols in `HttpCrawler`)
---
Missing:
- `Unpack[]`, union types and similar -> we might need `griffe` to parse the code better, `pydoc-markdown` stops at the return type "name", doesn't parse the syntax.
- Validation against the linked issue, see whether there's anything else missing
Relates #324

docs: improve autogenerated API docs

---

src/crawlee/_utils/requests.py
tests/unit/_utils/test_requests.py

- Adds headers in unique key computation
- Closes: #548 
- Added tests in [tests/unit/_utils/test_requests.py]

feat!: Add headers in unique key computation

---

src/crawlee/_types.py
src/crawlee/_utils/requests.py
tests/unit/_utils/test_requests.py

- Use strip in headers normalization.
- Remove redundant "defaults to" in docstrings.
- Improve `compute_unique_key` tests.
- N/A
- The "fix" is covered by tests now.

fix: use strip in headers normalization

---

docs/examples/code/fill_and_submit_web_form_crawler.py
docs/examples/code/fill_and_submit_web_form_request.py
docs/examples/fill_and_submit_web_form.mdx
src/crawlee/_request.py
src/crawlee/_types.py
src/crawlee/_utils/requests.py
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_httpx.py
src/crawlee/http_clients/curl_impersonate.py
src/crawlee/memory_storage_client/_request_queue_client.py
tests/unit/_utils/test_requests.py
tests/unit/http_crawler/test_http_crawler.py

- We had `data` and `payload` fields on the `Request` model.
- `payload` was not being provided to the HTTP clients, only the `data` field.
- ~In this PR, I'm merging them together, keeping only the `data` field (use the same naming as `HTTPX` & `CurlImpersonate`).~
- In this PR, I'm merging them together, keeping only the `payload` field (use the same naming as in JS Crawlee).
- ~I also defined type aliases for HTTP data and HTTP query parameters and used them across the project.~
- ~Some struggle with Pydantic & serialization, but should be OK now...~
- Reported by @honzajavorek on Slack
- Closes #560
- The current set of unit tests should cover the changes.

fix!: merge payload and data fields of Request

---

src/crawlee/_request.py
src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
src/crawlee/http_clients/_httpx.py
src/crawlee/http_clients/curl_impersonate.py
src/crawlee/http_crawler/_http_crawler.py
src/crawlee/parsel_crawler/_parsel_crawler.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/storages/_dataset.py
src/crawlee/storages/_key_value_store.py
src/crawlee/storages/_request_queue.py

- Improve API docs of all crawlers.
- Relates #304 
- The doc website was rendered locally.

docs: improve API docs of all crawlers

---

src/crawlee/proxy_configuration.py
tests/unit/proxy_configuration/test_new_proxy_info.py

Fixes an issue where the string `:None` was being appended to Playwright Proxy configurations.
```
proxy_info: {'server': 'http://p.webshare.io:None', 'username': 'foo', 'password': 'bar'}
```
Neither Firefox or Chrome were able to use a proxy URL like `http://foo:bar@p.webshare.io:80/`, because the :80 was being stripped off by HTTPX. `httpx.URL.port` cannot be set to 80 (for HTTP) or 443 (HTTPS), see example below.
This change explicitly sets the proxy port if it's unset.
```
In [1]: from httpx import URL
In [2]: url = URL(scheme="http", host="example.com", port=8080)
In [3]: url.port
Out[3]: 8080
In [4]: url = URL(scheme="http", host="example.com", port=80)
In [5]: url.port
In [6]: url = URL(scheme="http", host="example.com", port=443)
In [7]: url.port
Out[7]: 443
In [8]: url = …
```

fix: Default ProxyInfo port if httpx.URL port is None

---

.github/workflows/pre_release.yaml

- see discussion in https://github.com/apify/apify-client-js/pull/596#discussion_r1814782521

ci: Do not run pre-release in forks

---

docs/examples/code/playwright_crawler.py
docs/examples/playwright_crawler.mdx
src/crawlee/playwright_crawler/__init__.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/playwright_crawler/_playwright_crawling_context.py
src/crawlee/playwright_crawler/_playwright_pre_navigation_context.py
tests/unit/playwright_crawler/test_playwright_crawler.py

Add a new decorator for processing pre navigation hooks
Example Use:
```python
from crawlee.playwright_crawler import PlaywrightCrawler
from .routes import router
async def main() -> None:
"""The crawler entry point."""
crawler = PlaywrightCrawler(
request_handler=router,
max_requests_per_crawl=50,
)
@crawler.pre_navigation_hook
async def hooky(context) -> None:
print(f'Hook1')
@crawler.pre_navigation_hook
async def hooky2(context) -> None:
print(f'Hook2')
await crawler.run(
[
'https://crawlee.dev',
]
)
```
- Closes: #427

feat: Add `pre_navigation_hooks` to `PlaywrightCrawler`

---

src/crawlee/_request.py
tests/unit/storages/test_request_queue.py

This PR implements a new input parameter, always_enqueue, in the Request.from_url constructor. This feature allows users to bypass the request deduplication process, ensuring that each request is always enqueued and processed.
Key Changes:
- Added the always_enqueue parameter to the Request.from_url method.
- When always_enqueue is set to true, a random unique key is generated for each request, preventing it from being considered a duplicate.
- This enhancement provides users with a convenient way to enqueue requests without worrying about deduplication.
With this addition, users can seamlessly manage their requests while maintaining flexibility in their queuing strategy.
Fixes #547 
The modifications can be verified by making requests to the same URL. The operations should execute each …

feat: Add `always_enqueue` option to bypass URL deduplication

---

.gitignore
website/build_api_reference.sh
website/package.json
website/parse_types.py
website/pydoc-markdown/generate_ast.py
website/transformDocs.js
website/yarn.lock

Fixes more issues from #324 .
Namely: 
- Fixes broken GitHub links
- Correctly parses parameter / return types with Python's `ast` module
- Handles inheritance better (copies parent's docstring on `@override` methods)
- Using `@apify/docusaurus-plugin-typedoc-api@4.2.7`, expands the `Unpack` types and further simplifies other helper types (`NotRequired`, `Optional` etc.).

docs: smaller documentation fixes (GitHub links, type parsing etc.)

---

docs/examples/fill_and_submit_web_form.mdx
src/crawlee/_request.py
src/crawlee/_types.py
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_httpx.py
src/crawlee/http_clients/curl_impersonate.py
tests/unit/http_crawler/test_http_crawler.py

- Remove `Request.query_params` field.
- The URL params can be sent as a part of the URL and both our HTTP clients can handle it.
- Closes: #615
- Add a new test checking the URL query params.

chore!: Remove Request.query_params field

---

src/crawlee/_request.py
src/crawlee/basic_crawler/_basic_crawler.py
tests/unit/basic_crawler/test_basic_crawler.py

- Implements "max crawl depth"
- Closes: #460 
- Added tests

feat: Add `max_crawl_depth` property

---

src/crawlee/_autoscaling/snapshotter.py
src/crawlee/_autoscaling/types.py
src/crawlee/_utils/system.py
src/crawlee/events/_types.py
tests/unit/_autoscaling/test_snapshotter.py
tests/unit/_autoscaling/test_system_status.py

SDK passes max memory usage as `total_size`, and we don't actually use that field anyway, so let's just drop it

fix: Fix total_size usage in memory size monitoring

---

src/crawlee/_types.py
src/crawlee/storages/_dataset.py
tests/unit/basic_crawler/test_basic_crawler.py

We only checked the limit when committing the result, when the request handler was already considered successful. I added a check that results in an error before the request proceeds.

fix: Fix unhandled ValueError in request handler result processing

---

src/crawlee/beautifulsoup_crawler/__init__.py
src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py

To avoid repeating same Literal definitions.

feat: Add BeautifulSoupParser type alias

---

src/crawlee/configuration.py

docs: improve docs of the `Configuration` class

---

src/crawlee/playwright_crawler/_playwright_crawler.py
tests/unit/playwright_crawler/test_playwright_crawler.py

add `Request.headers` support for `PlaywrightCrawler`. 
The test uses `'https://httpbin.org/get' to ensure that the headers have been installed

fix: respect custom HTTP headers in `PlaywrightCrawler`

---

docs/examples/code/fill_and_submit_web_form_crawler.py
docs/examples/code/fill_and_submit_web_form_request.py
src/crawlee/_request.py
tests/unit/_memory_storage_client/test_request_queue_client.py

An incorrect serialization for `payload` is happening now. `payload` is represented as a byte string, but bytes cannot be serialized to json. Therefore, when loading and unloading from the queue (`_persist_single_request_to_storage`, `_json_to_request`) we get strings of format “b'test'”
Also corrected the documentation, as when filling forms the data should be passed not in json format and have the appropriate header.
- Closes: #668 
Updated `test_request_state_serialization` to also take `payload` into account when serializing and deserializing `Request`

fix: Fix serialization payload in Request. Fix Docs for Post Request

---

src/crawlee/_request.py
tests/unit/_memory_storage_client/test_request_queue_client.py
tests/unit/http_crawler/test_http_crawler.py

Correction of comments related to  PR #683
Add new tests for `http_crawler` different forms of `payload`
The test checks that the `payload` on the client side matches the data received by the server.
Also added verification that different types of `payload` are correctly handled on the client side and correctly recognized by the server with appropriate headers

chore: add tests for processing request payload

---

src/crawlee/_request.py

- This is a follow-up to https://github.com/apify/crawlee-python/issues/668#issuecomment-2476392555.
- Let's accept `payload` as both str and bytes in the `Request.from_url` constructor.
- The field `Request.payload` has a validator that accepts both. With this change, we are consistent in the `from_url` constructor as well.
- We do a similar thing for the `Request.headers` as well.

fix: Accept string payload in the Request constructor

---

pyproject.toml
src/crawlee/_request.py
src/crawlee/_utils/system.py
src/crawlee/base_storage_client/_models.py
src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
src/crawlee/configuration.py
src/crawlee/events/_event_manager.py
src/crawlee/events/_local_event_manager.py
src/crawlee/events/_types.py
src/crawlee/http_crawler/_http_crawler.py
src/crawlee/parsel_crawler/_parsel_crawler.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/sessions/_models.py
src/crawlee/statistics/_models.py

This allows to remove ruff exceptions, without breaking the ruff check. Also some exceptions were not necessary in the first place, so fix them.
See: https://docs.astral.sh/ruff/settings/#lint_flake8-type-checking_runtime-evaluated-base-classes

chore: Use runtime-evaluated-base-classes for ruff

---

src/crawlee/browsers/_browser_pool.py
src/crawlee/browsers/_playwright_browser_plugin.py
src/crawlee/playwright_crawler/_playwright_crawler.py

feat: Expose browser_options and page_options to PlaywrightCrawler

---

src/crawlee/_autoscaling/snapshotter.py
src/crawlee/_utils/context.py
src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/browsers/_base_browser_plugin.py
src/crawlee/browsers/_browser_pool.py
src/crawlee/browsers/_playwright_browser_plugin.py
src/crawlee/events/_event_manager.py
src/crawlee/playwright_crawler/_utils.py
src/crawlee/sessions/_session_pool.py
src/crawlee/statistics/_statistics.py
src/crawlee/storages/_request_queue.py
tests/unit/_autoscaling/test_autoscaled_pool.py
tests/unit/_autoscaling/test_snapshotter.py
tests/unit/browsers/test_browser_pool.py
tests/unit/browsers/test_playwright_browser_plugin.py
tests/unit/events/test_event_manager.py
tests/unit/http_crawler/test_http_crawler.py
tests/unit/sessions/test_session_pool.py

- The `EventManager` could be initialized multiple times, such as when running a `Crawler` wrapped inside an `Actor`.
- In `crawler.run`, the async context was entered and exited directly, which could lead to issues if the caller had already entered it. This scenario might occur when users provide their own instances of `BrowserPool`, `SessionPool`, `EventManager`, or others.
- Address these issues by introducing an `active` flag to the existing context managers to prevent multiple initializations.
- Implement an `ensure_context` helper and apply it to methods where context management is required.
- Fix & improve tests to ensure these cases are covered.
- I added missing names to asyncio tasks.

fix: Fix init of context managers and context handling in `BasicCrawler`

---

src/crawlee/configuration.py

- Fix docstring for `available_memory_ratio` because passing parameters to `Snapshotter` is already implemented
- Closes: #434

docs: fix docstring of `Configuration.available_memory_ratio`

---

src/crawlee/_request.py

- `BaseRequestData` does not have the `id` attribute.
- It is not breaking, as 
- `from_url` accepts `**kwargs`, 
- and `BaseRequestData` is not exposed to the public.

chore: Remove unused ID arg from `BaseRequestData.from_url`

---

src/crawlee/_autoscaling/autoscaled_pool.py
tests/unit/_autoscaling/test_autoscaled_pool.py

Concurrency ratio was not correctly used in Python version of autoscaled pool. Align it with the Javascript implementation of autoscaled pool.
Add test.
- Closes: #759

fix: Fix incorrect use of desired concurrency ratio

---

docs/upgrading/upgrading_to_v0x.md

This should have been part of https://github.com/apify/crawlee-python/pull/746

docs: Update upgrading guide for renamed BeautifulSoupParser

---

src/crawlee/http_clients/_httpx.py
tests/unit/basic_crawler/test_basic_crawler.py

- fix for passing `verify` to `transport` in `HttpxHttpClient`
- Closes: #798

fix: pass `verify` in httpx client

---

website/package.json
website/yarn.lock

Bumps the version of `@apify/docusaurus-plugin-typedoc-api` to use the patches from https://github.com/apify/docusaurus-plugin-typedoc-api/pull/34
This means that the documentation correctly resolves the `(grand)+parent `-inherited symbols.

docs: document inherited symbols properly

---

src/crawlee/storages/_request_queue.py

- fix event migrating handler and `is_finished` method in `RequestQueue` 
- Closes: #815

fix: fix event migrating handler in `RequestQueue`

---

docs/examples/code/beautifulsoup_crawler_stop.py
docs/examples/crawler_stop.mdx
src/crawlee/basic_crawler/_basic_crawler.py
tests/unit/basic_crawler/test_basic_crawler.py

This adds the possibility to stop crawler from user defined handler function.
Updated docs, added example.
Added test.
- Closes: #651

feat: Add stop method to BasicCrawler

---

src/crawlee/_utils/http.py
src/crawlee/abstract_http_crawler/_abstract_http_crawler.py
src/crawlee/basic_crawler/_basic_crawler.py
src/crawlee/errors.py
src/crawlee/http_clients/_base.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/sessions/_session.py
tests/unit/http_crawler/test_http_crawler.py

Fixes HTTP status code configuration behavior:
- `additional_http_error_status_codes`: Properly triggers errors and retries when specified status codes are encountered
- `ignore_http_error_status_codes`: Correctly treats specified error status codes as successful responses
- Closes: #756 
- closes #708

fix: respect user configuration for work with status codes

---

docs/examples/code/playwright_crawler.py
docs/upgrading/upgrading_to_v0x.md
src/crawlee/playwright_crawler/__init__.py
src/crawlee/playwright_crawler/_playwright_crawler.py
src/crawlee/playwright_crawler/_playwright_crawling_context.py
src/crawlee/playwright_crawler/_playwright_pre_nav_crawling_context.py
src/crawlee/playwright_crawler/_playwright_pre_navigation_crawling_context.py

- Rename `PlaywrightPreNavigationContext` to `PlaywrightPreNavigationCrawlingContext`.
- Of course, this is really long. Do we want to make it shorter, e.g.: `PlaywrightPreNavCrawlingContext`?
- Or make shorter all the crawling contexts... e.g. use just `CrawlContext`, (`PlaywrightPreNavCrawlContext`)
- Opinions?

refactor!: Rename PwPreNavContext to PwPreNavCrawlingContext

---

src/crawlee/basic_crawler/_basic_crawler.py

- Fix a situation where consecutive launches in the same session would immediately abort after an error exit

fix: `abort-on-error` for successive runs

---

src/crawlee/_service_locator.py
src/crawlee/errors.py
tests/unit/_memory_storage_client/test_memory_storage_client.py
tests/unit/basic_crawler/test_basic_crawler.py
tests/unit/conftest.py
tests/unit/test_service_locator.py

- this makes it possible to overwrite services in the service locator before they are retrieved for the first time
- closes #806

fix: Relax ServiceLocator restrictions

---

src/crawlee/request_loaders/_request_list.py
tests/unit/request_loaders/test_request_list.py

The old version of `RequestList` only updated the `_is_empty` flag on `fetch_next_request` calls, which was not enough. This PR updates it so that the `is_empty` method also tries to dequeue a request from the iterator before returning a result.

fix: Make result of RequestList.is_empty independent of fetch_next_request calls

---

src/crawlee/crawlers/_playwright/_playwright_crawler.py
website/package.json
website/yarn.lock

|before|after|
|---|---|
| ![obrazek](https://github.com/user-attachments/assets/be234c13-2cc6-443d-a0b9-990389868467) | ![obrazek](https://github.com/user-attachments/assets/87134dd0-0778-41a1-b5fc-209ad639f3cc) |
Bumps the `@apify/docusaurus-plugin-typedoc-api` package to the version with patched comment parsing (see https://github.com/apify/docusaurus-plugin-typedoc-api/pull/37)
The second commit turns naked links to Markdown links with the `[]()` syntax. This is purely for aesthetics (I didn't like seeing the same long URL twice under each other). If this is undesired - e.g. breaks something or goes against our style guide - I'm happy to revert.

docs: fix multiline `Args` documentation

---

src/crawlee/_types.py
src/crawlee/crawlers/_basic/_basic_crawler.py
src/crawlee/storages/_key_value_store.py
tests/unit/crawlers/_basic/test_basic_crawler.py
tests/unit/storages/test_key_value_store.py

Align Python implementation of `use_state` wirth JS
Add lock when accessing the cache or kvs to prevent race conditions.
Add unit tests for race conditions.
Remove key argument from `use_state` and hard code it to `BasicCrawler.CRAWLEE_STATE_KEY`. 
(Change in experimental feature is not marked as hard breaking with `!`.) 
- Closes: #856

fix: Avoid `use_state` race conditions. Remove key argument to `use_state`

---

src/crawlee/browsers/_playwright_browser_controller.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

- fix for proxy in PlaywrightCrawler 
- Closes: #887
- Added test to verify proxy is correctly set for PlaywrightCrawler

fix: restore proxy functionality for PlaywrightCrawler broken in v0.5

---

src/crawlee/_autoscaling/snapshotter.py
src/crawlee/_service_locator.py
src/crawlee/browsers/_playwright_browser_plugin.py
src/crawlee/configuration.py
src/crawlee/crawlers/_basic/_basic_crawler.py
src/crawlee/events/_event_manager.py
src/crawlee/events/_local_event_manager.py
src/crawlee/storage_clients/_memory/_memory_storage_client.py
tests/unit/_autoscaling/test_snapshotter.py
tests/unit/_autoscaling/test_system_status.py
tests/unit/browsers/test_playwright_browser_plugin.py
tests/unit/conftest.py
tests/unit/crawlers/_basic/test_basic_crawler.py

- Utilized all the `Configuration` fields, except for the `chrome_executable_path` and `xvfb`.
- Enhanced the `Configuration` fields documentation.
- Closes: #670

fix: Fix the usage of Configuration

---

src/crawlee/_autoscaling/autoscaled_pool.py
src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/_autoscaling/test_autoscaled_pool.py

- Convert unused `AutoscaledPool` input arguments into class constants.
- In a similar way, what we did to Snapshotter in https://github.com/apify/crawlee-python/pull/899.

chore: Convert unused AP input args into class consts

---

docs/guides/code/storages/rq_with_crawler_example.py
docs/guides/code/storages/rq_with_crawler_explicit_example.py
src/crawlee/_autoscaling/snapshotter.py
src/crawlee/_types.py
src/crawlee/_utils/http.py
src/crawlee/browsers/_base_browser_controller.py
src/crawlee/browsers/_base_browser_plugin.py
src/crawlee/browsers/_browser_pool.py
src/crawlee/browsers/_playwright_browser_controller.py
src/crawlee/browsers/_playwright_browser_plugin.py
src/crawlee/configuration.py
src/crawlee/crawlers/_basic/_basic_crawler.py
src/crawlee/events/_event_manager.py
src/crawlee/events/_local_event_manager.py
src/crawlee/request_loaders/_request_loader.py
src/crawlee/sessions/_session.py
src/crawlee/sessions/_session_pool.py
src/crawlee/statistics/_statistics.py
src/crawlee/storage_clients/_memory/_memory_storage_client.py
src/crawlee/storages/_dataset.py

- Update API docs of public components.
- Add functions (context/crawler helpers) to a "Functions" API docs section.
- Closes: #304
- The docs were rendered locally.

docs: Update API docs of public components

---

src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py

Fix crawler not retrying user handler if there was timeout in the handler.
Add parametrized test with one parameter set skipped with reason https://github.com/apify/crawlee-python/issues/908
- Closes: #907

fix: Fix crawler not retrying user handler if there was timeout in the handler

---

docs/examples/code/beautifulsoup_crawler_keep_alive.py
docs/examples/crawler_keep_alive.mdx
src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py

Add keep_alive flag to `crawler.__init__`
If True, this flag will keep crawler alive even when there are no more requests in queue. Crawler is then waiting for more requests to be added or to be explicitly stopped by `crawler.stop()`.
Add test, add code example in docs.
- Closes: #891

feat: Add keep_alive flag to `crawler.__init__`

---

src/crawlee/_utils/models.py
src/crawlee/events/_types.py

The Apify platform now sends a `timeRemainingSecs` property in the `MIGRATING` event data, this adds it to the event data model.

feat: add `time_remaining_secs` property to `MIGRATING` event data

---

src/crawlee/browsers/_browser_pool.py
src/crawlee/browsers/_playwright_browser_plugin.py

- Fix the `BrowserPool` and `PlaywrightBrowserPlugin` closures. Without it, the application crashes when `PlaywrightCrawler` is run in sequence again.

fix: fix `BrowserPool` and `PlaywrightBrowserPlugin` closure

---

Makefile
README.md
docs/deployment/apify_platform.mdx
docs/guides/http_clients.mdx
docs/guides/storages.mdx
docs/introduction/01_setting_up.mdx
docs/introduction/08_refactoring.mdx
docs/introduction/09_running_in_cloud.mdx
docs/quick-start/index.mdx
pyproject.toml
src/crawlee/project_template/{{cookiecutter.project_name}}/README.md
website/docusaurus.config.js
website/src/pages/index.js

- I updated the "Setting up" and "Running in cloud" pages to make them more beginner-friendly (hopefully) and also removed mentions of Poetry. Including Poetry was unnecessary and could be confusing. Not to mention in Python there are X other package managers that we could hypotetically mention as well. So I decided to stay only with Pip and Pipx for templates. People using a package manager other than Pip will likely know how to handle the installation on their own.
- This was reported on Slack by @honzajavorek.

docs: update setting up and running in cloud

---

src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py

- Fix cases where a session was not excluded from the pool after calling `session.retire()` inside a successful `request_handler`.

fix: fix session managment with retire

---

src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml
src/crawlee/project_template/{{cookiecutter.project_name}}/requirements.txt

Add poetry-plugin-export version constraint <1.9 to make it compatible with already constrained version of poetry <2
(poetry-plugin-export>=1.9 works only with poetry version >=2)
Fix incorrect camoufox cookiecutter template name in several template files 'camoufox'  -> 'playwright-camoufox'
- Closes: #951

fix: Fix templates - poetry-plugin-export version and camoufox template name

---

src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
src/crawlee/crawlers/_playwright/_playwright_crawler.py
tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
tests/unit/crawlers/_parsel/test_parsel_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

-  fix `enqueue_links` for response with redirect. 
- Closes: #955

fix: fix convert relative link to absolute in `enqueue_links` for response with redirect

---

.github/workflows/run_code_checks.yaml

Switches the `crawlee-python` unit tests to use the common service account for running the HTTPBin instance (and not the personal Apify account).
Uses the org-wide `APIFY_HTTPBIN_TOKEN` secret. It's possible that the personal acc token will shadow the org-wide secret - let's see how it works in the PR checks

chore: switch to the common self-hosted HTTPBin instance

---

src/crawlee/_autoscaling/snapshotter.py
src/crawlee/storage_clients/_base/_base_storage_client.py

- implement `_snapshot_client` for `Snapshotter`
- Closes: #60

feat: implement `_snapshot_client` for `Snapshotter`

---

docs/examples/code/adaptive_playwright_crawler.py
docs/examples/code/beautifulsoup_crawler.py
docs/examples/code/beautifulsoup_crawler_keep_alive.py
docs/examples/code/beautifulsoup_crawler_stop.py
docs/examples/code/crawl_website_with_relative_links_all_links.py
docs/examples/code/playwright_block_requests.py
docs/examples/code/playwright_crawler.py
docs/examples/code/playwright_crawler_with_camoufox.py
docs/examples/code/playwright_crawler_with_fingerprint_generator.py
docs/guides/code/playwright_crawler/browser_configuration_example.py
docs/guides/code/playwright_crawler/multiple_launch_example.py
docs/guides/code/playwright_crawler/pre_navigation_hook_example.py
docs/guides/code/proxy_management/tiers_bs_example.py
docs/guides/code/proxy_management/tiers_pw_example.py
docs/guides/code/storages/rq_basic_example.py
docs/guides/code/storages/rq_with_crawler_example.py
docs/guides/code/storages/rq_with_crawler_explicit_example.py
docs/introduction/code/03_transform_request.py
docs/introduction/code/04_sanity_check.py
docs/introduction/code/06_scraping.py
docs/introduction/code/07_final_code.py
docs/pyproject.toml
docs/quick-start/code/beautifulsoup_crawler_example.py
docs/quick-start/code/parsel_crawler_example.py
docs/quick-start/code/playwright_crawler_example.py

Set line length to docs related code to 90 to have each code example fully visible without the need to use slider.
Update existing examples to be compliant.
- Closes: #970

docs: Set line length to docs related code to 90

---

tests/unit/_utils/test_html_to_text.py
tests/unit/crawlers/_basic/test_basic_crawler.py

Replace unreliable `asyncio.sleep` in flaky `test_crawler_multiple_stops_in_parallel` by deterministic `asyncio.Barrier` and `asyncio.Semaphore`
Use explicit test name through `id=` in parametrized `test_html_to_text`  where parameter is several line long string. (To prevent strange test case name in logs.)

chore: Fix flakiness in test and use explicit test id

---

.github/workflows/pre_release.yaml

The current version skips the `build_and_deploy_docs` step (all steps, to be more precise) in the `pre_release` workflow for `docs:` commits, which is not correct.
This PR changes that so that we only avoid pushing to PyPI for `docs:` commits.

ci: Trigger docs build even after docs commits

---

.github/workflows/build_and_deploy_docs.yaml
CONTRIBUTING.md
pyproject.toml
uv.lock

- `project.urls`
- python 3.13 in ci
- unify name "Set up uv package manager"
- fix contributing guide
- add all extra, remove dev extra (move to dev deps)
- relates: #628

chore: fix uv setup

---

tests/unit/conftest.py
tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py
tests/unit/crawlers/_http/test_http_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py
tests/unit/storages/test_key_value_store.py

- Fix `kvs` isolation in the `use_state` test for `AdaptivePlaywrightCrawler` 
- Separate isolation cookie tests for `httpx` and `curl`. Having `httpx` use `respx` instead of `httpbin` will increase the stability of the test.
- Update some `PlaywrightCrawler` tests to use `route` instead of `httpbin`. This will speed up execution time and improve stability. It will also probably be useful for #929 in future

chore: fix tests and improve tests stability

---

src/crawlee/sessions/_models.py
src/crawlee/sessions/_session_pool.py
src/crawlee/statistics/_statistics.py
tests/unit/sessions/test_session_pool.py

Fix the "default" storage used for the migration.
It should not be named "default", it should have `None` name to create default storage.
- Closes: #991

fix: Fix default migration storage

---

src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
tests/unit/crawlers/_http/test_http_crawler.py
tests/unit/crawlers/_parsel/test_parsel_crawler.py

Set logger name for http based loggers to class name.
- Closes: #1021

fix: Fix logger name for http based loggers

---

website/docusaurus.config.js
website/package.json
website/yarn.lock

Bumps the `@apify/docusaurus-typedoc-plugin-api` to use the fixes in the latest versions. This unpacks the `Unpack`-typed arguments in the preparing stage (until now, this was done in rendering only). This slightly speeds up the on-page user experience, unifies the rendering in different components, and fixes issues with reexported symbols with `Unpack` arguments.
Includes support for `TypeAlias` (so soft-closes #1020 - although a manual check is recommended). 
Enables experimental features from `@docusaurus/faster` for faster build times.

docs: bump `typedoc-plugin`, use `@docusaurus/faster`

---

docs/upgrading/upgrading_to_v0x.md
src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
src/crawlee/crawlers/_basic/_basic_crawler.py
src/crawlee/crawlers/_playwright/_playwright_crawler.py
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_curl_impersonate.py
src/crawlee/http_clients/_httpx.py
src/crawlee/sessions/_session.py
tests/unit/crawlers/_http/test_http_crawler.py

* `additional_http_error_status_codes` and `ignore_http_error_status_codes` have been removed from the constructor parameters for HTTP clients
* The method `_raise_for_error_status_code` has been removed from `HttpClient` and its logic has been moved to `BasicCrawler`
* Prioritized checking of status codes that indicate `Session` blocking. Codes (401, 403, 429) trigger `retire` for the `Session` and retry, while other 4XX codes are handled as client errors (errors without retries).
* `additional_http_error_status_codes` is no longer used when checking status codes that indicate `Session` blocking. According to current documentation, these codes should trigger a retry, not `retire` for the `Session` and retry. Blocking status codes can be modified in `SessionPool` through …

refactor!: update status code handling

---

README.md
docs/introduction/01_setting_up.mdx
docs/upgrading/upgrading_to_v0x.md
pyproject.toml
src/crawlee/_cli.py
uv.lock
website/src/pages/index.js

- Restore entrypoint `crawlee` for `cli`
- Move cli dependencies to optional dependencies
- Closes: #1010
- Closes: #703
- Tested on a locally created wheel and local index
for pipx
```bash
pipx run --pip-args="--index-url http://localhost:8080" crawlee[cli] create
```
For uvx.
```bash
uvx --index-url http://localhost:8080 crawlee[cli] create
```

refactor!: move `cli` dependencies to optional dependencies

---

pyproject.toml
uv.lock

`Browserforge` is now used for header generation not only for `PlaywrightCrawler`, but also for http clients and so it needs to be mandatory dependency.

fix: Add `browserforge` to mandatory dependencies

---

.github/workflows/release.yaml

Previous optimization did not work as expected. Running checks always is safe and defensive approach.

chore: Always run checks in release workflow

---

src/crawlee/browsers/_playwright_browser.py
tests/unit/browsers/test_playwright_browser.py
tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py

- Fix a bug removing a temporary folder for non-headless mode. I saved an attempt to remove a folder on the `close` event, for when for some reason the browser crashes and the context is closed by the Playwright mechanisms

fix: Remove tmp folder for PlaywrightCrawler in non-headless mode

---

src/crawlee/_cli.py
src/crawlee/project_template/cookiecutter.json
src/crawlee/project_template/hooks/post_gen_project.py
src/crawlee/project_template/hooks/pre_gen_project.py
src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
src/crawlee/project_template/{{cookiecutter.project_name}}/README.md
src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml
uv.lock

- Add project template with `uv` package manager
- Closes: #1053

feat: add project template with `uv` package manager

---

src/crawlee/storage_clients/models.py
tests/unit/storages/test_dataset.py
tests/unit/storages/test_key_value_store.py
tests/unit/storages/test_request_queue.py
uv.lock

This PR follows up on https://github.com/apify/crawlee-python/pull/993. While aligning changes with the Apify SDK, I noticed that Pydantic models only select explicitly defined fields. However, we also need access to `urlSigningSecretKey`, so I’ve updated the `StorageMetadata` config **to allow extra fields.**
Added tests for all storage types (datasets, key-value stores, and request queues) to ensure extra attributes are correctly handled.

refactor: allow extra attributes for storages

---

src/crawlee/crawlers/_basic/_basic_crawler.py

- Add a check thread before set `add_signal_handler`. Since `add_signal_handler` [can only be set in the main thread](https://docs.python.org/3/library/asyncio-eventloop.html#:~:text=Like%20signal.signal()%2C%20this%20function%20must%20be%20invoked%20in%20the%20main%20thread.).

fix: add a check thread before set `add_signal_handler`

---

Makefile
pyproject.toml
src/crawlee/_browserforge_workaround.py
src/crawlee/browsers/__init__.py
src/crawlee/fingerprint_suite/__init__.py
uv.lock

This temporary fix is patching `browserforge` on import time.
This is needed until issue in the upstream repo is fixed to avoid downloading files when importing `browserforge`.
Same fix is added to two `__init__ `files of packages that through import chain trigger the undesired file download.
- Relates to: apify/apify-sdk-python/issues/423

fix: Temporary workaround for `browserforge` import time code execution

---

pyproject.toml
uv.lock

Explicitly add `sortedcontainers` to the project dependencies.
It is already being used in code, but so far it was not explicitly mentioned due to `sortedcollections` already being in project dependencies.
`sortedcontainers` is dependency of `sortedcollections` and thus it was kind of implictly present in the project.

chore: Add `sortedcontainers` to the project dependencies

---

src/crawlee/router.py
uv.lock

- Update API docs of Router
- Closes: #1098

chore: update API docs of Router

---

src/crawlee/_cli.py
src/crawlee/project_template/hooks/pre_gen_project.py

- Add checks to ensure that the selected package manager is installed and executable.
- Suppress cookie-cutter logs when a failure occurs.
- Closes: #1138
- Output before:
```
- Before:
```$ uvx crawlee[cli] create --crawler-type parsel --http-client httpx --package-manager poetry --start-url 'https://crawlee.dev/' --no-apify my-crawler
⠋ Bootstrapping...Traceback (most recent call last):
File "/tmp/tmpd9wekhuy.py", line 9, in <module>
version = subprocess.check_output([manager, '--version']).decode().strip()
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.13/subprocess.py", line 474, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**kwargs).stdout
^^^^^^^^^
File …

fix: Improve validation errors in Crawlee CLI

---

src/crawlee/storage_clients/models.py
tests/unit/storage_clients/_memory/test_memory_storage_client.py

Update `UnprocessedRequest` to match actual data.
Add test.
- Closes: #1150

fix: Update `UnprocessedRequest` to match actual data

---

src/crawlee/crawlers/_playwright/_playwright_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

- For `PlaywrightCrawler`, cookies should only be saved to the session store when the handler is fully executed. This is because the browser may continue to set cookies while the handler is being executed
- Add a test simulating the installation of a cookie in the browser during the `default_handler` execution process
- Update the `test_isolation_cookies` test

fix: Fix the order in which cookies are saved to the `SessionCookies` and the handler is executed for `PlaywrightCrawler`

---

src/crawlee/storages/_request_queue.py
tests/unit/storages/test_request_queue.py

Adds retry to unprocessed requests in call `add_requests_batched`.
Retry calls recursively `_process_batch`, which initially works on full request batch and then on batches of unprocessed requests until retry limit is reached or all requests are processed. Each retry is done after linearly increasing delay with each attempt.
Unprocessed requests are not counted in `request_queue.get_total_count`
Add test.
- Closes: [Handle unprocessed requests in batch_add_requests](https://github.com/apify/apify-sdk-python/issues/456)

feat: Handle unprocessed requests in `add_requests_batched`

---

src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py
uv.lock

- Call `failed_request_handler` for `SessionError` when session rotation count exceeds maximum

fix: call `failed_request_handler` for `SessionError` when session rotation count exceeds maximum

---

docs/guides/code_examples/error_handling/change_handle_error_status.py
docs/guides/code_examples/error_handling/disable_retry.py
docs/guides/code_examples/error_handling/handle_proxy_error.py
docs/guides/error_handling.mdx

- add guide about error handling

docs: add guide about error handling

---

src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
tests/unit/crawlers/_parsel/test_parsel_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

Update `test_enqueue_links` to use test server.
(The test was still using real page instead of test server and the test started being blocked by `Cloudflare` when running in CI)

chore: Update `test_enqueue_links` to use test server 

---

src/crawlee/statistics/_error_tracker.py
tests/unit/_statistics/test_error_tracker.py

- Fix getting an error message for errors not having message data in `args`. If the error was raised in a chain, tries to get the previous error message from `__context__`. Otherwise uses the error class name as the message.
- Closes: #1179 
- Add new tests

fix: fix handle error without `args` in `_get_error_message`  for `ErrorTracker`

---

docs/guides/code_examples/running_in_web_server/crawler.py
docs/guides/code_examples/running_in_web_server/server.py
docs/guides/running_in_web_server.mdx
pyproject.toml

Add guide for running crawler in web server
- Closes: #1148

docs: Add guide for running crawler in web server

---

src/crawlee/crawlers/_basic/_basic_crawler.py

Improves the option documentation based on [discussion](https://github.com/apify/crawlee-python/issues/1171).
Follow-up after https://github.com/apify/crawlee/pull/2957.

docs: improve `max_request_retries` and `max_session_rotations` documentation

---

src/crawlee/crawlers/_playwright/_playwright_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

It is not possible to apply `Configuration` to the Playwright crawler (see issue). This is a proposal for a solution.
- Closes: #1185 
Added a test that failed before the fix, but works now.

fix: Allow config change on `PlaywrightCrawler`

---

src/crawlee/_types.py
src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py

- add `payload` in `SendRequestFunction` for support `POST` request
- Related: #1201

fix: add `payload` to `SendRequestFunction` to support `POST` request

---

src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py

- Fixes match check for specified enqueue strategy for requests with redirect. Before this PR, the check used the final url after the redirect, after that the original url will be used.
- Closes: #1198
- Added tests for enqueue strategy with redirect simulation.

fix: fix match check for specified enqueue strategy for requests with redirect

---

src/crawlee/project_template/{{cookiecutter.project_name}}/{{cookiecutter.__package_name}}/__main__.py

- Sets `WindowsSelectorEventLoopPolicy` only for templates that use curl-impersonate, provided that playwright is not used. Since curl-impersonate does not support `ProactorEventLoop` used in Windows.
For all other cases, `ProactorEventLoop` is recommended for Windows.
- Closes: #1204

fix: set `WindowsSelectorEventLoopPolicy` only for curl-impersonate template without `playwright`

---

src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
src/crawlee/crawlers/_playwright/_playwright_crawler.py
tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
tests/unit/crawlers/_parsel/test_parsel_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

- Fix support `EnqueueLinksKwargs` parameters for `extract_links` function
- Closes: #1212

fix: respect `EnqueueLinksKwargs` for `extract_links` function

---

src/crawlee/_utils/urls.py
src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
src/crawlee/crawlers/_basic/_basic_crawler.py
src/crawlee/crawlers/_playwright/_playwright_crawler.py

- The goal of the refactoring is to create a new helper function to check `EnqueueLinksKwargs`, for use elsewhere in the code. The new function works as an iterator, to better fit the application as a filter.
- Also updated related functions that currently have `EnqueueLinksKwargs` check logic: `extract_links` and `_commit_request_handler_result`.

refactor: add enqueue links filter iterator

---

pyproject.toml
uv.lock

```
PytestConfigWarning: Unknown config option: timeout
```
We use pytest timeout in pytest config, let's add the `pytest-timeout` plugin.

chore: fix `PytestConfigWarning` by adding `pytest-timeout`

---

src/crawlee/crawlers/_beautifulsoup/_utils.py
tests/unit/_utils/test_html_to_text.py
uv.lock

```
GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
```
Use `lxml` explicitly. If this becomes an issue for someone, we can expose the parser option.

chore: fix `GuessedAtParserWarning` in BeautifulSoup

---

src/crawlee/statistics/_statistics.py
tests/unit/_statistics/test_request_processing_record.py

Replace `datetime.now` by `time.perf_counter_ns` in time difference calculations for request duration tracking to avoid possible issues  connected to measured time resolution.
This fixes the flakiness of `test_final_statistics` that was happening on Windows and Python versions < 3.13.
- Closes: #1256
Newly added test was stress tested 500x times on old implementation to see the test sensitivity. On the source code before this PR the new test failed for Windows and Python versions 3.9,3.10,3.11,3.12 all 500 times. It did not fail even once for Linux or Windows  + Python 3.13.

fix: Use `perf_counter_ns` for request duration tracking

---

src/crawlee/browsers/_browser_controller.py
src/crawlee/browsers/_browser_pool.py
src/crawlee/browsers/_playwright_browser_controller.py
tests/unit/browsers/test_browser_pool.py

- Add `retire_browser_after_page_count` parameter for `BrowserPool`

feat: Add `retire_browser_after_page_count` parameter for `BrowserPool`

---

pyproject.toml

- Use well-known labels for project URLs (where possible).
- https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels

chore: use well known labels for project.urls

---

docs/guides/code_examples/creating_web_archive/manual_archiving_parsel_crawler.py
docs/guides/code_examples/creating_web_archive/manual_archiving_playwright_crawler.py
docs/guides/code_examples/creating_web_archive/simple_pw_through_proxy_pywb_server.py
docs/guides/creating_web_archive.mdx
pyproject.toml

Add guide about creating and using WARC files with `Crawlee`
- Closes: #1262

docs: Add guide about creating and using WARC files with `Crawlee`

---

src/crawlee/_cli.py
src/crawlee/project_template/cookiecutter.json
src/crawlee/project_template/hooks/post_gen_project.py
tests/e2e/project_template/test_static_crawlers_templates.py
tests/unit/test_cli.py

- Add `crawlee-cli` option to skip project installation -  skips Python packages installation and Playwright installation.
- Remove `manual` value from package_manager `crawlee-cli` option
- Closes: #1122

feat: Add crawlee-cli option to skip project installation

---

docs/examples/code_examples/fill_and_submit_web_form_crawler.py
docs/guides/code_examples/creating_web_archive/manual_archiving_parsel_crawler.py
docs/guides/code_examples/error_handling/change_handle_error_status.py
docs/guides/code_examples/login_crawler/http_login.py
docs/guides/code_examples/session_management/sm_basic.py
docs/guides/code_examples/session_management/sm_http.py
docs/upgrading/upgrading_to_v1.md
src/crawlee/_utils/robots.py
src/crawlee/crawlers/_abstract_http/_http_crawling_context.py
src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_parser.py
src/crawlee/crawlers/_http/_http_crawler.py
src/crawlee/crawlers/_http/_http_parser.py
src/crawlee/crawlers/_parsel/_parsel_parser.py
src/crawlee/crawlers/_playwright/_types.py
src/crawlee/http_clients/_base.py
src/crawlee/http_clients/_curl_impersonate.py
src/crawlee/http_clients/_httpx.py
tests/unit/crawlers/_basic/test_basic_crawler.py
tests/unit/crawlers/_http/test_http_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py
tests/unit/http_clients/test_curl_impersonate.py
tests/unit/http_clients/test_httpx.py

- Makes the `read` method for `HttpResponse` asynchronous. This is more consistent in a fully asynchronous framework. More flexible than a synchronous method

refactor!: Change method `HttpResponse.read` from sync to async

---

src/crawlee/_utils/system.py
tests/unit/_utils/test_system.py

- Use `pss` for memory estimation only on Linux.
- Use `rss` for memory estimation only on MacOs.
- Closes: #1329

fix: Fix memory estimation not working on MacOS

---

src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py
tests/unit/crawlers/_http/test_http_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

The argument  `max_request_retries` of  `BasicCrawler` previously included also the initial request in retries. Now it counts only the retries.
- Closes: #1326

fix: Fix retry count to not count the original request

---

src/crawlee/sessions/_cookies.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py
tests/unit/server.py

- Ignore unknown parameters passed in cookies
- Closes: #1333
- Added a test that sets `Partitioned` cookies. To reproduce the behaviour that causes Playwright to throw an error

fix: Ignore unknown parameters passed in cookies

---

src/crawlee/_types.py
src/crawlee/storage_clients/_base/_dataset_client.py
src/crawlee/storage_clients/_file_system/_dataset_client.py
src/crawlee/storage_clients/_memory/_dataset_client.py
src/crawlee/storages/_dataset.py

because of https://github.com/apify/apify-client-python/pull/467

refactor!: Change Dataset unwind parameter to accept list of strings

---

pyproject.toml
src/crawlee/_autoscaling/snapshotter.py
tests/unit/_autoscaling/test_snapshotter.py
uv.lock

- Remove `sortedcollections` and `sortedcontainers` packages from dependencies.
- Replace the sorted list in the Snapshotter with a custom class.
- Closes: #1077
- One new test for the `SortedSnapshotList` plus the current test set covers the changes.

chore: Remove sortedcollections and sortedcontainers packages

---

CHANGELOG.md
pyproject.toml
uv.lock

This basically reverts https://github.com/apify/crawlee-python/commit/0dfbad56744c412885ee8956d4ec88c947fcec2f. Since we don't have a proper RC pipeline, I used the standard one, which resulted in this commit.

chore: Cleanup after 1.0.0rc1 release

---

src/crawlee/_request.py
src/crawlee/_types.py
src/crawlee/_utils/system.py
src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler_statistics.py
src/crawlee/crawlers/_adaptive_playwright/_rendering_type_predictor.py
src/crawlee/events/_types.py
src/crawlee/fingerprint_suite/_types.py
src/crawlee/request_loaders/_request_list.py
src/crawlee/request_loaders/_sitemap_request_loader.py
src/crawlee/sessions/_models.py
src/crawlee/statistics/_models.py
src/crawlee/storage_clients/models.py

- Since we have bumped the minimum version of pydantic to 2.11, using `populate_by_name` is [not recommended](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name).

chore: Replace `populate_by_name` with `validate_by_name` and `validate_by_alias` for Pydantic `ConfigDict`

---

src/crawlee/_types.py
src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py
tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
tests/unit/crawlers/_parsel/test_parsel_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

- Add support for specifying RQ dst for `add_requests` and `enqueue_links` methods
- Closes: #1402

feat: Add RQ id, name, alias args to `add_requests` and `enqueue_links` methods

---

src/crawlee/storage_clients/_base/_storage_client.py
src/crawlee/storage_clients/_file_system/_storage_client.py
src/crawlee/storages/_dataset.py
src/crawlee/storages/_key_value_store.py
src/crawlee/storages/_request_queue.py
src/crawlee/storages/_storage_instance_manager.py

- `StorageClient` type is not an individual storage key and is instead used in an additional cache key (can be overridden).
- This allows `StorageClients` to have better control over caching.
- Enables: https://github.com/apify/apify-sdk-python/issues/513
- Unit tests

refactor: Give more instance caching flexibility to the storage clients

---

src/crawlee/_types.py
src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
src/crawlee/crawlers/_playwright/_playwright_crawler.py
tests/unit/_autoscaling/test_autoscaled_pool.py
tests/unit/crawlers/_basic/test_basic_crawler.py
tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
tests/unit/crawlers/_http/test_http_crawler.py
tests/unit/crawlers/_parsel/test_parsel_crawler.py
tests/unit/crawlers/_playwright/test_playwright_crawler.py

- Set default desired concurrency for non-browser crawlers to 10.
- The default desired concurrency for browser crawlers stays at 1.
- The default maximum concurrency is set to 100.
- Based on the Slack discussion https://apify.slack.com/archives/CD0SF6KD4/p1756993901117969.

fix: Set default desired concurrency for non-browser crawlers to 10

---

src/crawlee/crawlers/_basic/_basic_crawler.py
tests/unit/crawlers/_basic/test_basic_crawler.py

- Prevent `request_manager` change in `BasicCrawler` after crawler restart.
- Added unit test

chore: Prevent request manager change after crawler restart

---

docs/upgrading/upgrading_to_v1.md
src/crawlee/storages/_base.py
src/crawlee/storages/_dataset.py
src/crawlee/storages/_key_value_store.py
src/crawlee/storages/_request_queue.py
src/crawlee/storages/_storage_instance_manager.py
src/crawlee/storages/_utils.py
tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
tests/unit/otel/test_crawler_instrumentor.py
tests/unit/sessions/test_session_pool.py
tests/unit/storage_clients/_file_system/test_fs_dataset_client.py
tests/unit/storage_clients/_file_system/test_fs_kvs_client.py
tests/unit/storage_clients/_file_system/test_fs_rq_client.py
tests/unit/storage_clients/_memory/test_memory_dataset_client.py
tests/unit/storage_clients/_memory/test_memory_kvs_client.py
tests/unit/storage_clients/_memory/test_memory_rq_client.py
tests/unit/storage_clients/_sql/test_sql_dataset_client.py
tests/unit/storage_clients/_sql/test_sql_kvs_client.py
tests/unit/storage_clients/_sql/test_sql_rq_client.py
tests/unit/storages/test_dataset.py
tests/unit/storages/test_key_value_store.py
tests/unit/storages/test_request_queue.py

- Added name validation for storages in accordance with Apify platform restrictions
- Closes: #1434
- Relates: #1354 
- Added new tests to verify correct validation.

fix: Add storages name validation

---

tests/unit/otel/test_crawler_instrumentor.py

chore: Skip flaky Windows test test_crawler_instrumentor_capability
