CHANGELOG.md, src/crawlee/basic_crawler/basic_crawler.py, tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py, tests/unit/playwright_crawler/test_playwright_crawler.py
=> fix: handling of relative URLs in add_requests

src/crawlee/autoscaling/autoscaled_pool.py
=> fix: Improve AutoscaledPool state management

docs/introduction/04-real-world-project.md, docs/introduction/05-crawling.md, docs/introduction/06-scraping.md, website/sidebars.js
- docs: add real-world project page
- docs: add crawling page
- docs: add scraping page
- #170 
- N/A
=> doc: add 3 more pages to the introduction doc section

docs/introduction/06-scraping.md, docs/introduction/07-saving-data.md, docs/introduction/08-refactoring.md, docs/introduction/09-running-in-cloud.md, website/sidebars.js
- doc: add 2 last pages to the introduction doc section
- closes #170 
- all code examples were tested
- doc website was launched locally
=> doc: add 2 last pages to the introduction doc section

renovate.json, website/package.json, website/yarn.lock
=> ci: setup branch auto-merge via renovate

README.md, docs/introduction/01-setting-up.mdx
Added an additional universal entry point command for spinning up crawlee
- Added an additional crawlee starting command
- Related: https://github.com/apify/crawlee-python/issues/285
=> docs: mention running the CLI after installation

docs/guides/proxy_management.mdx, docs/guides/proxy_management_examples/tiers_beautifulsoup.py, docs/guides/proxy_management_examples/tiers_playwright.py, src/crawlee/proxy_configuration.py
=> doc: tiered proxy urls

CHANGELOG.md, src/crawlee/basic_crawler/types.py, src/crawlee/playwright_crawler/playwright_crawler.py, src/crawlee/playwright_crawler/types.py
- Add blocking detection for `PlaywrightCrawler`.
- Improve documentation of the `PlaywrightCrawler` and related components.
- Closes: #239
- Only manual, until we have https://github.com/apify/crawlee-python/issues/197 ready.
=> feat: blocking detection for playwright crawler

src/crawlee/beautifulsoup_crawler/__init__.py, src/crawlee/browsers/__init__.py, src/crawlee/playwright_crawler/__init__.py
wrong command in the log: 'pip install crawlee[playwright]', it should be "pip install 'crawlee[playwright]'"
- N/A
- N/A
=> bug: minor log fix

src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py, src/crawlee/playwright_crawler/playwright_crawler.py
=> fix: Strip whitespace from href in enqueue_links

CHANGELOG.md, src/crawlee/_utils/requests.py, src/crawlee/_utils/urls.py, src/crawlee/basic_crawler/basic_crawler.py, src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py, src/crawlee/http_clients/httpx_client.py, src/crawlee/models.py, src/crawlee/playwright_crawler/playwright_crawler.py, src/crawlee/proxy_configuration.py, tests/unit/_utils/test_urls.py, tests/unit/basic_crawler/test_basic_crawler.py, tests/unit/basic_crawler/test_context_pipeline.py, tests/unit/basic_crawler/test_router.py, tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py, tests/unit/http_crawler/test_http_crawler.py, tests/unit/memory_storage_client/test_request_queue_client.py, tests/unit/playwright_crawler/test_playwright_crawler.py, tests/unit/storages/test_request_queue.py
- Add [HttpUrl](https://docs.pydantic.dev/latest/api/networks/#pydantic.networks.HttpUrl) Pydantic type for URLs - URL validation.
- A lot of tests had to be adjusted.
- Some changes regarding relative/absolute URLs had to be implemented as well.
- Closes: #300
- N/A
=> feat: add URL validation

website/docusaurus.config.js
change announcment to webinar.
=> docs: change announcement

tests/unit/basic_crawler/test_basic_crawler.py, tests/unit/memory_storage_client/test_memory_storage_client.py
This was done during investigation of #351
=> test: Test persist_storage more thoroughly

README.md
add webinar announcement to readme.
=> docs: add webinar to readme

website/docusaurus.config.js
=> docs: short banner

cliff.toml, src/crawlee/playwright_crawler/playwright_crawler.py, src/crawlee/playwright_crawler/types.py, src/crawlee/playwright_crawler/utils.py
This implements a bare bones infinite scroll helper. It is also added into the crawling context.
=> feat(playwright): `infinite_scroll` helper

pyproject.toml
=> chore: bump version to 0.2.1

website/docusaurus.config.js
=> docs: remove banner

README.md
=> docs: remove-webinar

README.md, docs/examples/add-data-to-dataset.mdx, docs/examples/beautifulsoup-crawler.mdx, docs/examples/capture-screenshot-using-playwright.mdx, docs/examples/crawl-all-links-on-website.mdx, docs/examples/crawl-multiple-urls.mdx, docs/examples/crawl-specific-links-on-website.mdx, docs/examples/crawl-website-with-relative-links.mdx, docs/examples/export-entire-dataset-to-file.mdx, docs/examples/parsel-crawler.mdx, docs/examples/playwright-crawler.mdx, docs/guides/http_clients.mdx, docs/guides/proxy_management.mdx, docs/introduction/01-setting-up.mdx, docs/introduction/02-first-crawler.mdx, docs/introduction/03-adding-more-urls.mdx, docs/introduction/04-real-world-project.mdx, docs/introduction/05-crawling.mdx, docs/introduction/06-scraping.mdx, docs/introduction/07-saving-data.mdx, docs/introduction/08-refactoring.mdx, docs/introduction/index.mdx, docs/quick-start/index.mdx
- doc: add links to API doc in suitable places
- Closes: #266
- Doc website was rendered locally
=> docs: add links to API doc in suitable places

.github/workflows/run_release.yaml, pyproject.toml, src/crawlee/_autoscaling/snapshotter.py, src/crawlee/_request.py, tests/unit/_memory_storage_client/test_memory_storage_client.py, tests/unit/conftest.py
- Update links in `pyproject.toml`.
- Update links to repository (to `crawlee-python`).
- Closes: N/A
- N/A
=> chore: update project links & repository references

docs/deployment/apify_platform.mdx, docs/deployment/code/apify_platform_get_public_url.py, docs/deployment/code/apify_platform_main.py, docs/introduction/09_running_in_cloud.mdx, docs/introduction/code/09_apify_sdk.py, docs/introduction/code/routes.py, pyproject.toml, templates/beautifulsoup/.dockerignore, templates/beautifulsoup/.gitignore, templates/beautifulsoup/Dockerfile, templates/playwright/.dockerignore, templates/playwright/.gitignore, templates/playwright/Dockerfile, website/sidebars.js
Added a doc page about running crawlers on Apify using the SDK. I tested it, fixes will be required before publishing this.
=> docs: Deployment guide

templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py, templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/main.py, templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py, templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py, templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/main.py, templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
=> refactor: use same file structure as in Actor templates

docs/guides/code/request_storage_do_not_purge.py, docs/guides/code/request_storage_helper_add_requests.py, docs/guides/code/request_storage_helper_enqueue_links.py, docs/guides/code/request_storage_purge_explicitly.py, docs/guides/code/request_storage_rl_basic.py, docs/guides/code/request_storage_rl_with_crawler.py, docs/guides/code/request_storage_rq_basic.py, docs/guides/code/request_storage_rq_with_crawler.py, docs/guides/code/request_storage_rq_with_crawler_explicit.py, docs/guides/request_storage.mdx
- Add request storage guide. 
- It is highly inspired by the TS version.
- Closes: #355
- Closes: #478
- It was rendered locally.
=> docs: add request storage guide

src/crawlee/_request.py
=> docs: improve docstring of Request class

src/crawlee/_request.py, tests/unit/basic_crawler/test_basic_crawler.py, tests/unit/storages/test_request_queue.py
- resolves #524
This adds validation to `Request.user_data` so that the user cannot pass in data that is not JSON-serializable.
=> fix: Improve `Request.user_data` serialization

.pre-commit-config.yaml
=> chore: remove unit tests from pre-commit config

.github/workflows/_check_changelog_entry.yaml, .github/workflows/_check_docs_build.yaml, .github/workflows/_linting.yaml, .github/workflows/_publish_to_pypi.yaml, .github/workflows/_type_checking.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/docs.yaml, .github/workflows/run_release.yaml
=> ci: install Poetry to setup-python environment

.github/workflows/_check_changelog_entry.yaml, .github/workflows/_check_docs_build.yaml, .github/workflows/_linting.yaml, .github/workflows/_publish_to_pypi.yaml, .github/workflows/_type_checking.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/docs.yaml, .github/workflows/run_release.yaml
=> ci: use python version instead of executable path

.github/workflows/build_and_deploy_docs.yaml, Makefile
Semi-reverts latest changes to the CI setup to fix the docs build.
=> docs: try to fix the CI documentation build

src/crawlee/basic_crawler/_basic_crawler.py, src/crawlee/events/_event_manager.py
=> docs: Update input arg docstrings of `BasicCrawler` and `EventManager`

website/docusaurus.config.js, website/src/pages/index.js
few changes on homepage for SEO as requested by marketing
=> docs: homepage changes

src/crawlee/_types.py, src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py, src/crawlee/parsel_crawler/_parsel_crawler.py, src/crawlee/playwright_crawler/_playwright_crawler.py, tests/unit/basic_crawler/test_basic_crawler.py
Docstrings & some (internal) name alignments.
=> chore: update identifiers & API docs in `_types` module

src/crawlee/__init__.py
=> fix: Add HttpHeaders to module exports

src/crawlee/_request.py, src/crawlee/_types.py, src/crawlee/basic_crawler/_basic_crawler.py, src/crawlee/http_clients/_base.py, src/crawlee/http_clients/_httpx.py, src/crawlee/http_clients/curl_impersonate.py
Relates to https://github.com/apify/crawlee-python/issues/663
=> chore: make HTTP headers more user friendly

src/crawlee/basic_crawler/_basic_crawler.py, tests/unit/basic_crawler/test_basic_crawler.py
- Implement `abort_on_error` aborting execution when an error occurs
- Closes: #704 
- Implemented a new unit test
=> feat: add `abort_on_error` property

tests/unit/basic_crawler/test_basic_crawler.py
=> chore: Skip flaky test

src/crawlee/storages/_key_value_store.py, tests/unit/basic_crawler/test_basic_crawler.py
- Fix circular imports occurring after using `service_container` in `KeyValueStore`
- Closes: #804
=> fix: fix circular import in `KeyValueStore`

docs/examples/beautifulsoup_crawler.mdx, docs/examples/code/beautifulsoup_crawler.py, docs/examples/code/parsel_crawler.py, docs/examples/parsel_crawler.mdx, src/crawlee/abstract_http_crawler/_abstract_http_crawler.py, tests/unit/http_crawler/test_http_crawler.py
This makes it possible for users to register their pre-navigation hooks for http based crawlers. 
Add tests.
Update docs.
- Closes: #635
=> feat: Add pre-navigation hooks router to AbstractHttpCrawler

tests/unit/storages/test_key_value_store.py
Update test_get_auto_saved_value_auto_save to reduce flakiness.
Introduce time tolerance to the test.
=> chore: Update test_get_auto_saved_value_auto_save to reduce flakiness

README.md
Importing changed with V0.5.0 of Crawlee.
=> docs: Fix crawler imports in readme

src/crawlee/_types.py
- Update docs for `selector` in `EnqueueLinksFunction`
=> docs: update `selector` description for `EnqueueLinksFunction`

docs/examples/code/playwright_crawler_with_camoufox.py
```
TypeError: camoufox.async_api.AsyncNewBrowser() got multiple values for keyword argument 'headless'
```
=> docs: Fix Playwright + Camoufox code example

docs/guides/code/playwright_crawler/browser_configuration_example.py, docs/guides/code/playwright_crawler/multiple_launch_example.py, docs/guides/code/playwright_crawler/plugin_browser_configuration_example.py, docs/guides/code/playwright_crawler/pre_navigation_hook_example.py, docs/guides/playwright_crawler.mdx
- Add guide for PlaywrightCrawler and BrowserPool
- Closes: #477
=> docs: add guide for PlaywrightCrawler and BrowserPool

tests/unit/crawlers/_http/test_http_crawler.py, tests/unit/crawlers/_playwright/test_playwright_crawler.py
- Improve cookies tests for more stability
- Update `parametrize` in http crawler tests for use `pytest.param`
=> chore: improve http crawler tests and cookies tests

src/crawlee/project_template/templates/routes_playwright.py, src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile, src/crawlee/project_template/{{cookiecutter.project_name}}/{{cookiecutter.__package_name}}/__main__.py
=> fix: Fix playwright template and dockerfile

src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
=> fix: Fix installing dependencies via pip in project template

docs/guides/avoid_blocking.mdx, docs/guides/code/browser_fingerprint/default_fingerprint_generator_with_args.py, docs/guides/code/browser_fingerprint/playwright_with_fingerprint_generator.py
Add anti-blocking guide for Python.
(Adaptation of JS version of the guide: https://crawlee.dev/docs/guides/avoid-blocking)
- Closes: #481
=> docs: Add anti-blocking guide

docs/upgrading/upgrading_to_v0x.md, src/crawlee/_log_config.py, src/crawlee/configuration.py
=> refactor!: remove unused config properties

.github/workflows/build_and_deploy_docs.yaml, .github/workflows/pre_release.yaml, .github/workflows/release.yaml, .github/workflows/run_code_checks.yaml
- Relates: https://github.com/apify/crawlee-python/issues/628
=> ci: switch apify workflow branch back to main

tests/unit/http_clients/test_curl_impersonate.py, tests/unit/http_clients/test_httpx.py
- Update tests for redirects so that they work correctly on the internal `httpbin` instance used in CI.
=> chore: update redirect tests

src/crawlee/project_template/hooks/pre_gen_project.py, src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile, src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml, uv.lock
- Relax version poetry in template
- Closes: #954
=> fix: update project templates for Poetry v2.x compatibility

pyproject.toml, src/crawlee/_utils/console.py, src/crawlee/statistics/_models.py, tests/unit/_utils/test_console.py, uv.lock
- Add a small utility for create a text table
- Remove `rich` from the required dependencies
- Closes: #1082
=> chore(deps): replace `rich` with an internal utility

src/crawlee/crawlers/_basic/_basic_crawler.py
- add port for `same-origin` strategy check
=> fix: add port for `same-origin` strategy check

docs/deployment/code_examples/google/google_example.py, docs/deployment/google_cloud.mdx, pyproject.toml, website/sidebars.js
- add deploy guide for google functions
- Closes: #707
=> docs: add deploy guide for google functions

tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py, tests/unit/storages/test_request_manager_tandem.py
```
PytestCollectionWarning: cannot collect test class 'TestInput' because it has a __init__ constructor
@dataclass
```
=> chore: fix `PytestCollectionWarning` by adding `__test__=False`

Makefile
=> chore: Fix incremental test coverage

docs/upgrading/upgrading_to_v1.md
-  add `impit` in upgrade guide
=> docs: Add `impit` to upgrade guide

src/crawlee/sessions/_cookies.py
- add `partitionKey` in `PlaywrightCookieParam`
=> chore: add `partitionKey` in `PlaywrightCookieParam`

src/crawlee/project_template/{{cookiecutter.project_name}}/pyproject.toml, src/crawlee/project_template/{{cookiecutter.project_name}}/requirements.txt
- Update templates to handle optional httpx client.
- Running E2E template tests
=> fix: Update templates to handle optional httpx client
